### ISSUE TITLE
Make styled components server side

### ISSUE THREAD

**Issue by alexadark** [alexadark/frontity-starter-project#5]
So we can use Grommet

**Comment by luisherranz** [comment]
I've been taking a look and the [babel macro support](https://styled-components.com/docs/tooling#babel-macro) doesn't cover server-side rendering, only the features offered by the [babel plugin](https://styled-components.com/docs/tooling#babel-plugin).

It also looks like Styled-Components, in contrast to Emotion, still requires you to add JavaScript commands to your server for SSR: https://styled-components.com/docs/advanced#server-side-rendering

Supporting styled-components only by itself doesn't make much sense because all the features are included in Emotion. So we are only talking about supporting styled-components to support the UI libraries that use styled-components instead of emotion.

We have some possibilities here:
1. Add support for styled-components SSR.
I don't think this makes much sense because we will increase the bundle size of Frontity unnecessarily.
2. Translate the styled-components API to emotion.
This makes more sense but we still need to figure out how we are going to deal with [Theming](https://community.frontity.org/t/theming/883) in Frontity to translate the `ThemeProvider` and `withTheme` parts.
3. Don't support styled-components based UI libraries at all.

I'll keep thinking about it.

**Comment by luisherranz** [comment]
I've created a Feature Discussion in our topic to keep track of this conversation: https://community.frontity.org/t/ui-libraries-based-on-styled-components/1381
